export type Project = { slug:string; title:string; location:string; year:string; category:string[]; services:string[]; description:string; status:string; clientType:string };

export const products = [
  {number:"01",title:"Intelligence",eyebrow:"Decision platform",text:"Property analysis, scenario modeling and professional reporting for individuals and focused teams.",href:"/intelligence",cta:"Launch Intelligence"},
  {number:"02",title:"Enterprise Suite",eyebrow:"Institutional operating system",text:"Controlled workflows, governance and decision intelligence across real-estate, finance, agriculture and technology.",href:"/enterprise",cta:"Enter Enterprise Suite"},
  {number:"03",title:"Studio",eyebrow:"Architecture + advisory",text:"Architecture, interiors, façades, master planning and development strategy shaped as one discipline.",href:"/studio",cta:"Explore the Studio"},
];

export const projects: Project[] = [
  {slug:"arcadian-courtyard",title:"Arcadian Courtyard",location:"Mediterranean Coast",year:"2026",category:["Architecture","Hospitality"],services:["Architecture","Interiors","Development consulting"],description:"A climate-responsive hospitality study organized around shade, water and a sequence of protected courtyards.",status:"Concept",clientType:"Private developer"},
  {slug:"meridian-house",title:"Meridian House",location:"North America",year:"2025",category:["Residential","Interior"],services:["Architecture","Interior architecture"],description:"A residential prototype where structure, daylight and material restraint define the rooms.",status:"Design development",clientType:"Private client"},
  {slug:"agora-institute",title:"Agora Institute",location:"West Africa",year:"2026",category:["Institutional","Master Planning"],services:["Master planning","Architecture","Strategic advisory"],description:"A phased academic district designed for civic life, adaptable teaching and long-term institutional growth.",status:"Feasibility",clientType:"Academic institution"},
];

export const faqs = [
  ["Structūra","What is Structūra?","An integrated architecture, real-estate intelligence and enterprise technology company."],
  ["Intelligence","Who is Intelligence for?","Investors, brokers, developers, students, analysts and small teams evaluating real-estate decisions."],
  ["Enterprise Suite","How is Enterprise different?","Enterprise adds institutional operations, permissions, collaboration, governance and auditability."],
  ["Studio","What work does the Studio undertake?","Architecture, interiors, façades, master planning, renovation, visualization and strategic advisory."],
  ["Security","Does Structūra claim certifications?","No. Deployment and security requirements are assessed for each controlled institutional engagement."],
  ["Partnerships","Can institutions partner with Structūra?","Yes. We welcome aligned technology, academic, government, financial and research inquiries."],
];

export const genericPages: Record<string,{eyebrow:string;title:string;intro:string;sections:{title:string;text:string}[]}> = {
  about:{eyebrow:"About Structūra",title:"Architecture where design, capital and identity intersect.",intro:"Structūra is an international architectural and spatial advisory firm specializing in high-value environments.",sections:[{title:"Montréal headquarters",text:"Headquartered at 204 Rue du St-Sacrement in Old Montréal, Structūra is active across North America, the Caribbean, Europe and emerging markets."},{title:"The House of the Architect",text:"Our strategic design core integrates architectural design, spatial intelligence, material strategy, 3D modelling and execution advisory into one coherent system."},{title:"International practice",text:"We work across residential, commercial, institutional, hospitality and strategic development environments with cultural intelligence and local care."},{title:"Enduring value",text:"Architecture is approached as strategic positioning: shaping how assets are perceived, experienced and valued over time."}]},
  partnerships:{eyebrow:"Partnerships",title:"Align architecture, capital and execution.",intro:"Structūra engages selectively with partners whose long-term development vision matches the discipline of the House.",sections:[{title:"Institutions + governments",text:"Architectural and spatial advisory for civic, educational, cultural and transportation environments requiring regulatory precision and representational clarity."},{title:"Developers + builders",text:"Early alignment of program, zoning, circulation, façade articulation, financial viability and buildability across residential, mixed-use and institutional developments."},{title:"Capital partners",text:"Structured collaboration with investors, lenders and asset managers focused on feasibility transparency, spatial efficiency, long-term value and reduced execution risk."}]},
  investors:{eyebrow:"Investor relations",title:"Architecture as a value multiplier.",intro:"Structūra works at the convergence of design, capital structure and development positioning.",sections:[{title:"Investors + developers",text:"Feasibility evaluation, spatial optimization and strategic phasing help transform land and underperforming assets into coherent, market-positioned developments."},{title:"Financial institutions",text:"Pre-construction advisory and design validation strengthen feasibility transparency, development discipline and the spatial assumptions behind project economics."},{title:"Asset managers",text:"Repositioning, renovation, façade modernization and circulation strategy can strengthen tenant experience, pricing power and long-term asset perception."},{title:"Selective engagement",text:"Confidential discussions concerning development partnerships, institutional initiatives and structured capital collaboration are reviewed directly by the firm."}]},
  careers:{eyebrow:"Careers",title:"Work across boundaries.",intro:"We are interested in people who combine depth in one field with genuine curiosity about the others.",sections:[{title:"Disciplines",text:"Architecture, real estate, finance, engineering, product design, software and institutional strategy."},{title:"Open inquiry",text:"Current openings will be published here. Exceptional general applications may be submitted through Contact."}]},
};
