"use client";
import Link from 'next/link';
import {useState} from 'react';
import {motion,AnimatePresence} from 'motion/react';
import type {Dispatch,Role} from '../content/editorial';

export function DispatchArchive({items}:{items:Dispatch[]}){const[filter,setFilter]=useState('All');const categories=['All',...Array.from(new Set(items.map(x=>x.category)))];const visible=filter==='All'?items:items.filter(x=>x.category===filter);return <section className="dispatch-archive"><div className="editorial-filters">{categories.map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><AnimatePresence mode="popLayout">{visible.map((x,i)=><motion.article layout initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} key={x.slug} className="dispatch-row"><span>{String(i+1).padStart(2,'0')} / {x.category}</span><div><h2>{x.title}</h2><p>{x.dek}</p></div><Link href={`/dispatches/${x.slug}`}>Read dispatch ↗</Link></motion.article>)}</AnimatePresence><div className="dispatch-note">The archive reflects verified public Structūra publications only. New writing will appear here as it is released.</div></section>}

export function CareersBoard({items}:{items:Role[]}){const[filter,setFilter]=useState('All');const disciplines=['All',...Array.from(new Set(items.map(x=>x.discipline)))];const visible=filter==='All'?items:items.filter(x=>x.discipline===filter);return <section className="careers-board"><div className="editorial-filters">{disciplines.map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div>{visible.map(x=><Link className="role-row" href={`/careers/${x.slug}`} key={x.slug}><span>{x.discipline}</span><h2>{x.title}</h2><p>{x.location}</p><b>{x.status}</b><i>↗</i></Link>)}</section>}

export function ApplicationForm({role}:{role:string}){const[state,setState]=useState('');async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setState('Submitting…');const res=await fetch('/api/careers',{method:'POST',body:new FormData(e.currentTarget)});const data=await res.json();setState(data.message||data.error)}return <form className="application-form" onSubmit={submit}><input type="hidden" name="role" value={role}/><label>Name<input required name="name" minLength={2}/></label><label>Email<input required name="email" type="email"/></label><label>Portfolio URL<input name="portfolio" type="url" placeholder="https://"/></label><label className="full">Statement<textarea required name="statement" minLength={80} rows={7} placeholder="Tell us how your work and thinking align with this future opportunity."/></label><label className="full upload">CV / portfolio PDF<input name="document" type="file" accept=".pdf"/></label><label className="full consent"><input required name="consent" type="checkbox"/> I consent to Structūra reviewing this submission for future opportunities.</label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off"/><button className="button dark">Submit expression of interest</button>{state&&<p className="form-state">{state}</p>}</form>}
