"use client";
import Link from 'next/link';
import {useMemo,useState} from 'react';
import {motion,AnimatePresence} from 'motion/react';
import type {Project} from '../content/site';

export function ProjectScene({type,compact=false,view='hero'}:{type:Project['visualSceneType'];compact?:boolean;view?:'hero'|'site'|'exterior'|'interior'|'detail'}){const base=`/projects/${type}`;return <div className={`project-scene rendered-scene scene-${type} view-${view} ${compact?'compact':''}`} aria-hidden="true"><picture><source type="image/avif" srcSet={`${base}-960.avif 960w, ${base}-1920.avif 1920w`}/><source type="image/webp" srcSet={`${base}-960.webp 960w, ${base}-1920.webp 1920w`}/><img src={`${base}-1920.webp`} alt="" loading={compact?'lazy':'eager'} decoding="async" sizes={compact?'(max-width: 900px) 100vw, 50vw':'100vw'}/></picture><div className="project-plates">{['EXTERIOR','SPATIAL','MATERIAL','SITE'].map((label,i)=><span key={label} style={{backgroundImage:`url(${base}-960.webp)`,'--plate':i} as React.CSSProperties}><i>0{i+1} / {label}</i></span>)}</div><div className="rendered-grade"/></div>}

export function PortfolioExperience({projects,filters}:{projects:Project[];filters:string[]}){const [active,setActive]=useState('All');const visible=useMemo(()=>active==='All'?projects:projects.filter(p=>p.categories.includes(active)),[active,projects]);return <>
 <div className="portfolio-filters" role="toolbar" aria-label="Filter portfolio">{['All',...filters].map(f=><button key={f} className={active===f?'active':''} onClick={()=>setActive(f)} aria-pressed={active===f}>{f}</button>)}</div>
 <div className="portfolio-scenes" aria-live="polite"><AnimatePresence mode="popLayout">{visible.map((p,i)=><motion.article layout initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}} transition={{duration:.45}} className="portfolio-study" key={p.slug}><ProjectScene type={p.visualSceneType} compact/><div className="study-index">{String(i+1).padStart(2,'0')} / {String(visible.length).padStart(2,'0')}</div><div className="study-copy"><p>{p.categories.join(' · ')}</p><h2>{p.title}</h2><p>{p.location} · {p.status}</p><p>{p.summary}</p><div><Link href={`/studio/portfolio/${p.slug}`}>Examine project ↗</Link><Link href={`/booking?type=${p.inquiryType}&project=${p.slug}`}>Request consultation ↗</Link></div></div></motion.article>)}</AnimatePresence>{visible.length===0&&<div className="portfolio-empty"><p>No study currently occupies this category.</p><button onClick={()=>setActive('All')}>Return to all work</button></div>}</div>
 </>}
