"use client";
import Link from "next/link";
import {useState} from "react";

const nav=[['Intelligence','/intelligence'],['Enterprise','/enterprise'],['Studio','/studio'],['About','/about'],['Partnerships','/partnerships'],['Investors','/investors']];
export function Header(){const [open,setOpen]=useState(false); return <header className="header"><Link className="logo" href="/" aria-label="Structūra home">STRUCTŪRA</Link><nav aria-label="Main navigation" className={open?'nav open':'nav'}>{nav.map(([a,b])=><Link key={b} href={b} onClick={()=>setOpen(false)}>{a}</Link>)}</nav><div className="header-actions"><Link href="/contact">Contact</Link><a className="button dark" href={process.env.NEXT_PUBLIC_ENTERPRISE_SUITE_URL||'/enterprise'}>Enter Suite</a></div><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation"><span/><span/></button></header>}
export function Footer(){return <footer><div><Link className="logo light" href="/">STRUCTŪRA</Link><p>Architecture, intelligence and enterprise systems for consequential decisions.</p><address>204 Rue du St-Sacrement<br/>Old Montréal, QC H2Y 1W8<br/><a href="tel:+15144308865">+1 514 430 8865</a></address></div><div className="footer-links"><div><b>Explore</b><Link href="/intelligence">Intelligence</Link><Link href="/enterprise">Enterprise</Link><Link href="/studio">Studio</Link><Link href="/studio/portfolio">Portfolio</Link></div><div><b>Institution</b><Link href="/about">About</Link><Link href="/partnerships">Partnerships</Link><Link href="/investors">Investors</Link><Link href="/careers">Careers</Link></div><div><b>Information</b><Link href="/faq">FAQ</Link><Link href="/accessibility">Accessibility</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></div><div className="footer-base"><span>© 2026 Structūra</span><span>Built for the long term.</span></div></footer>}
export function CookieBanner(){const [show,setShow]=useState(()=>typeof window!=="undefined"&&!localStorage.getItem('structura-consent'));if(!show)return null;const choose=(v:string)=>{localStorage.setItem('structura-consent',v);setShow(false)};return <aside className="cookie" aria-label="Cookie preferences"><p><b>Your privacy, precisely considered.</b><br/>Necessary cookies support the site. Analytics are optional.</p><div><button onClick={()=>choose('necessary')}>Necessary only</button><button className="button dark" onClick={()=>choose('all')}>Accept analytics</button></div></aside>}
export function SiteShell({children}:{children:React.ReactNode}){return <><a className="skip" href="#main">Skip to content</a><Header/><main id="main">{children}</main><Footer/><CookieBanner/></>}
