import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ContactForm,CTA,SectionHead,SystemVisual} from '../../components/Sections';
import {PortfolioExperience,ProjectScene} from '../../components/PortfolioExperience';
import {BookingForm} from '../../components/BookingForm';
import {faqs,genericPages,portfolioFilters,projects} from '../../content/site';
type Props={params:Promise<{slug?:string[]}>};
const productData={intelligence:{eyebrow:'Structūra Intelligence',title:'Analyze any opportunity.',intro:'Fast, professional real-estate analysis for individuals and focused teams.',sections:[['Scenario modeling','Compare acquisition, development and financing structures without losing the assumptions behind them.'],['Financial intelligence','Calculate NOI, cap rate and IRR; compare outcomes and trace each result to its inputs.'],['Market context','Place property and scenario information beside relevant market signals for a more complete review.'],['Risk review','Identify sensitivities, constraints and unanswered questions before a decision is committed.']]},enterprise:{eyebrow:'Structūra Enterprise Suite',title:'Institutional clarity, by design.',intro:'A controlled operating environment connecting specialized terminals through Structūra Core.',sections:[['Structūra Core','The shared intelligence and coordination layer across S-RED, S-FIN, S-AGRO and S-TECH.'],['Four terminals','Specialized environments for real estate, finance, agriculture and technology.'],['Administrative governance','Organization structure, role-based access and managed institutional workflows.'],['Auditability','Important actions and assumptions remain reviewable within controlled deployments.']]}} as const;
const studioSections=[['Architecture','SITE → PROGRAM → GEOMETRY → FOUNDATION → STRUCTURE → ENVELOPE → MATERIAL → ENVIRONMENT → BUILDING'],['Interior architecture','FORM → SPACE → MATERIAL → LIGHT → EXPERIENCE'],['Exterior + façade','MASS → STRUCTURE → SKIN → CLIMATE → IDENTITY'],['Master planning','TERRAIN → ACCESS → DISTRICTS → INFRASTRUCTURE → PHASES → PLACE']];
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug=[]}=await params;const title=slug.map(x=>x[0].toUpperCase()+x.slice(1)).join(' / ')||'Structūra';return{title,description:`${title} at Structūra — architecture, real-estate intelligence and enterprise technology.`}}
export default async function Page({params}:Props){const {slug=[]}=await params;const path=slug.join('/');
 if(path==='booking')return <><section className="booking-hero"><p className="kicker">Private consultation / Montréal · Global</p><h1>Bring the project<br/><em>into focus.</em></h1><p>Share the context, scale and ambition. Every request is reviewed before the appropriate discipline responds.</p></section><section className="booking-section"><BookingForm/><aside><p className="kicker">Direct office</p><address>204 Rue du St-Sacrement<br/>Old Montréal, QC H2Y 1W8<br/><a href="tel:+15144308865">+1 514 430 8865</a></address><p>Project information is used only to evaluate and respond to the inquiry.</p></aside></section></>;
 if(path.startsWith('studio/portfolio/')&&slug[2]){const p=projects.find(x=>x.slug===slug[2]);if(!p)notFound();const related=p.relatedProjects.map(s=>projects.find(x=>x.slug===s)).filter(Boolean);return <><section className="project-detail-hero"><ProjectScene type={p.visualSceneType}/><div><p className="kicker">{p.categories.join(' / ')}</p><h1>{p.title}</h1><p>{p.location} · {p.status} · {p.year}</p></div></section><section className="project-intro"><p className="kicker">Project statement</p><h2>{p.summary}</h2><Link className="button dark" href={`/booking?type=${p.inquiryType}&project=${p.slug}`}>Request consultation</Link></section><section className="project-sequence"><ProjectScene type={p.visualSceneType}/><div className="sequence-labels">{['TERRAIN','SITE','ACCESS','MASSING','STRUCTURE','MATERIAL','ENVIRONMENT'].map((x,i)=><span key={x}>0{i+1} {x}</span>)}</div></section><section className="project-strategies">{[['Design intent',p.designIntent],['Site strategy',p.siteStrategy],['Material approach',p.materialStrategy],['Development logic',p.developmentStrategy]].map(([a,b])=><article key={a}><p className="kicker">{a}</p><h2>{b}</h2></article>)}</section><section className="related-projects"><SectionHead eyebrow="Related studies" title="Continue through the work."/><div>{related.map(r=>r&&<Link key={r.slug} href={`/studio/portfolio/${r.slug}`}><ProjectScene type={r.visualSceneType} compact/><span>{r.title} ↗</span></Link>)}</div></section><CTA/></>}
 if(path==='studio/portfolio')return <><section className="page-hero portfolio-hero"><p className="kicker">Studio / Portfolio</p><h1>Work is a record of decisions.</h1><p>Built work, current initiatives, proposals and concept studies—each labeled according to its actual status.</p></section><section className="portfolio-experience"><PortfolioExperience projects={projects} filters={portfolioFilters}/></section><section className="initiatives-title"><p className="kicker">Dedicated collection</p><h2>International Development Initiatives</h2><p>Current initiatives and strategic proposals. These studies are not presented as completed buildings.</p><div className="initiative-collection">{projects.filter(p=>p.initiative).map(p=><Link href={`/studio/portfolio/${p.slug}`} key={p.slug}><ProjectScene type={p.visualSceneType} compact/><div><span>{p.status}</span><h3>{p.title}</h3><p>{p.location} · {p.categories.join(' / ')}</p></div></Link>)}</div></section></>;
 if(path==='studio'||path.startsWith('studio/'))return <><section className="page-hero"><p className="kicker">Structūra Studio</p><h1>Architecture as an integrated act.</h1><p>Design, development intelligence and strategic advisory shaped around human experience and long-term consequence.</p></section>{studioSections.map((x,i)=><section className="discipline living-discipline" key={x[0]}><div><p className="kicker">0{i+1} / Discipline</p><h2>{x[0]}</h2><p className="process-line">{x[1]}</p><p>Each engagement moves from evidence and intent toward precise spatial, material and economic decisions.</p><Link href={`/booking?type=${i===3?'master-planning':i===1?'interior-design-consultation':'architectural-consultation'}`}>Request consultation ↗</Link></div><div className="discipline-scene"><ProjectScene type={i===1?'interior':i===3?'agriculture':'concept'}/><div className="construction-labels">{x[1].split(' → ').map((s,j)=><span key={s} style={{'--i':j} as React.CSSProperties}>{s}</span>)}</div></div></section>)}<section><SectionHead eyebrow="Portfolio" title="Selected work and active studies."/><Link className="button dark" href="/studio/portfolio">View portfolio</Link></section><CTA/></>;
 if(path in productData){const d=productData[path as keyof typeof productData];return <><section className="page-hero"><p className="kicker">{d.eyebrow}</p><h1>{d.title}</h1><p>{d.intro}</p></section><section className="content-sections">{d.sections.map(x=><article className="content-card" key={x[0]}><h2>{x[0]}</h2><p>{x[1]}</p></article>)}</section><CTA/></>}
 if(path==='contact')return <><section className="page-hero"><p className="kicker">Contact</p><h1>Direct the inquiry precisely.</h1><p>For a structured project request, use the consultation form. General correspondence may be sent below.</p><Link className="button dark" href="/booking">Book a consultation</Link></section><section><ContactForm/></section></>;
 if(path==='faq')return <><section className="page-hero"><p className="kicker">Frequently asked questions</p><h1>Clear questions. Direct answers.</h1></section><section className="faq">{faqs.map(x=><details key={x[1]}><summary>{x[1]}</summary><p><small>{x[0]}</small><br/>{x[2]}</p></details>)}</section></>;
 const legal=['privacy','cookies','legal','terms','accessibility'];if(legal.includes(path))return <><section className="page-hero"><p className="kicker">Information / {path}</p><h1>{path==='accessibility'?'Accessibility statement':path[0].toUpperCase()+path.slice(1)}</h1><p>Transparent standards for how this public website is used and maintained.</p></section></>;
 const g=genericPages[path];if(g)return <><section className="page-hero"><p className="kicker">{g.eyebrow}</p><h1>{g.title}</h1><p>{g.intro}</p></section><section className="content-sections">{g.sections.map(x=><article className="content-card" key={x.title}><h2>{x.title}</h2><p>{x.text}</p></article>)}</section>{path==='partnerships'&&<Link className="button dark" href="/booking?type=partnership-inquiry">Partnership inquiry</Link>}{path==='investors'&&<Link className="button dark" href="/booking?type=investor-inquiry">Investor inquiry</Link>}<CTA/></>;notFound()}
